workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          npm install -g create-react-app
          
      - name: Build
        script: |
          brew update
          brew install node
          npm install -g npm@latest
          npm run build
          npm run deploy
