workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: CD
        script: |
          ls 
      - name: Build
        script: |
          npm run build
          npm run deploy
