workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          cd ./
          npm install create-react-app ./cashappimproved/
          
      - name: Build
        script: |
          npm run build
          npm run deploy
