            - name: iOS Build Action for react native
  # You may pin to the exact commit or the version.
  # uses: talha-irshad-kodexo/ios-build-action@49ba14913220729ff3d0c09025c664378441897b
  uses: talha-irshad-kodexo/ios-build-action@1.0.1
  with:
    # Project path
    project-path: 
    # For example, iOS Distribution
    code-signing-identity: 
    # Team id
    team-id: 
    # Workspace pathy
    workspace-path: # optional, default is 
    # Choose app-store, ad-hoc, package, enterprise, development, or developer-id
    export-method: # optional, default is app-store
    # For example, Debug, Release
    configuration: # optional, default is Release
    # Certificate password
    certificate-password: # optional, default is 
    # Output path of ipa
    output-path: # optional, default is output.ipa
    # Scheme
    scheme: # optional, default is 
    # Targets to be updated with mobileprovision, code signing identity, etc
    update-targets: # optional, default is 
    # Deprecated, use update-targets instead
    disable-targets: # optional, default is 
    # Path to an export options plist
    export-options: # optional, default is 
    # The SDK that should be used for building the application
    build-sdk: # optional, default is 
    # Use a custom destination for building the app
    build-destination: # optional, default is 
    # Path for Swift Package Manager dependencies
    cloned-source-packages-path: # optional, default is 
          
